[package]
name = "json-lexer"
version = "0.1.0"
authors = ["wyx0-xyz <wyxo.bs09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
